<?php

$title = 'Spells';
$this->headTitle($title);
$this->headMeta()->appendName('description', 'Overview and details of all RPG-spells available');              

$this->inlineScript()->appendFile('/js/spells.js', 'text/javascript');

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p></p>


<table>
<?php 
    foreach($this->spells as $spell): 
        echo $this->partial('partial/spellrow', array('spell' => $spell)); 
    endforeach; 
?>
</table>

<?php $this->placeholder('buttons')->captureStart(); ?>
<a class="mainmenu" href="/spell/edit/">Create New</a>
<?php $this->placeholder('buttons')->captureEnd() ?>