<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Erik\'s D20 Database', 'PREPEND')->setSeparator(' - '); 
        
            echo $this->headMeta()->appendName('author', 'Erik')
                                  ->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/generalscripts.js')
                                      ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

   </head>
    <body>
        <div id="container">
            <div class="liststyle" id="textcontainer">
            <?php echo $this->content; ?>
                <div id="sitedescription">Erik's D20-database</div>  
                <div id="menubar">
                    <a class="menuhome" href="/">Home</a>
                    <?php echo $this->placeholder('buttons'); ?></div>
            </div>
            <div class="hidden" id="sidbar"></div>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
